server:
  port: 8081
spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8847
        username: nacos
        password: nacos
    gateway:
      enabled: true
      routes:
        - id: auth
          uri: lb://auth
          predicates:
            - Path=/auth/**
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/lisihong?serverTimezone=UTC&characterEncoding=UTF-8
mybatis-plus:
  mapper-locations: classpath*:mappers/*.xml
canal:
  host: 127.0.0.1
  port: 11111
  destination: example
  subscribe: lisihong.cloud_role_license,lisihong.cloud_api_license